name: 'docker-image-updater'
description: 'Update image versions inside docker compose files'
branding:
  icon: 'corner-right-up'
  color: 'green'
inputs:
  dry:
    description: 'Do not create a pull request with the changes, just output them'
    required: false
    default: 'false'
outputs:
  plan:
    description: 'Plan of the changes to be commited'
runs:
  using: 'docker'
  # image: docker://ghcr.io/fopina/action-docker-image-updater:latest
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ secrets.TOKEN }}
