name: 'docker-image-updater'
description: 'Update image versions inside docker compose files'
branding:
  icon: 'corner-right-up'
  color: 'green'
inputs:
  token:
    description: Token with enough permissions to open pull requests in your repository
    required: true
  file-match:
    description: Glob to match compose files
    default: '**/docker-compose.y*ml'
  dry:
    description: 'Do not create a pull request with the changes, just output them'
    default: 'false'
  extra-fields:
    description: JSON dictionary with field names mapped to their image, templated with tag and version
    required: false
outputs:
  plan:
    description: 'Plan of the changes to be commited'
runs:
  using: 'docker'
  image: docker://ghcr.io/fopina/action-docker-image-updater:v1
  # image: 'Dockerfile'
