name: 🧪 tests

on:
  workflow_call:
  push:
    paths-ignore:
      - .github/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 
        run: |
          pip install pipenv
          pipenv requirements --dev > reqs.txt
          pip install -r reqs.txt

      - name: Lint check
        id: lint-check
        # allow unit tests to run even if this fails
        continue-on-error: true
        run: |
          make lint-check

      - name: Run unit tests
        run: |
          make test
      
      - name: Final check
        if: ${{ steps.lint-check.outcome == 'failure' }}
        run: |
          echo Lint check failed, check its log
          exit 1
     
      - name: Force local build
        run: |
          sed -i 's/^  image\:.*/  image\: Dockerfile/g' action.yml  

      - name: Integration test 1
        uses: ./
        id: it1
        with:
          token: "${{ github.token }}"
          dry: 'true'

      - name: Integration test 2
        uses: ./
        id: it2
        with:
          token: "${{ github.token }}"
          file-match: '**/*.yml'
          dry: 'true'
      
      - name: Integration test 3
        uses: ./
        id: it3
        with:
          token: "${{ github.token }}"
          file-match: '**/*.yml'
          extra-fields: >
            {
              "portainer_version": "portainer/portainer-ce:?-alpine",
              "portainer_agent_version": "portainer/agent:?-alpine"
            }
          dry: 'true'

      - name: print out plan
        env:
          PLAN: ${{ steps.it2.outputs.plan }}
        run:
          echo "$PLAN"

      - name: Assert integration test
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: |
          pytest tests/integration.py
